// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "6d01f38a67cc1e0b6a7b1f42833cc39d4acae7c4b571865beeb07ca9f1ccfc7b")
